apiVersion: v1
kind: ConfigMap
metadata:
  name: env-variables
data:
  SYNC_PERIOD_MINUTES: "5"
  NOMIRROR: "true"
  #WORKERS: "3"
  REINDEX: "3" # automatically reindex in 3 min, default 10
  INDEXER_OPT: "--progress"
  OPENGROK_VERBOSE: "--verbose"
  OPENGROK_PROGRESS: "--progress"
  #OPENGROK_PARALLELISM: "3"
  JAVA_OPTS: >-
    -Djava.util.logging.config.file=/opengrok-log-config/logging.properties
    -XX:+UnlockExperimentalVMOptions
    -Xmx8g
    -XX:-HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/usr/local/tomcat/logs/memory.dump
    -XX:MaxMetaspaceSize=1g
    -Djava.awt.headless=true
    -XX:+AlwaysPreTouch
    