apiVersion: v1
kind: Service
metadata:
  name: opengrok-clusterip
spec:
  selector:
    app: opengrok
  #type: ClusterIP
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080